server:
  port: 8082

spring:
  application:
    name: noticeboard-service

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: ronit
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



